---

python_user_venv_user: "{{ rpims_user }}"
python_user_venv_path: "/home/{{ rpims_user }}/.venv"
python_user_venv_python: "/usr/bin/python3"

python_user_venv_packages:
  - pip
  - wheel
  - setuptools
  - RPi.bme280
  - smbus2
  - w1thermsensor
  - "redis[hiredis]"
  - pid
  - PyYAML
  - ruamel.yaml
  - luma.oled
  - luma.lcd
  - systemd
  - adafruit-circuitpython-ads1x15
  - adafruit-circuitpython-dht
  - automationhat
  - setproctitle
  - rshell
  - pyusb
  - flask
  - gunicorn
  - packaging

grove_repo_url: "https://github.com/Seeed-Studio/grove.py"
grove_repo_dest: "~/tmp/grove.py"
