---
mediamtx_version: "1.16.1"

mediamtx_install_dir: "/usr/local/bin"
mediamtx_config_dir: "/etc/mediamtx"
mediamtx_service_name: "mediamtx"
mediamtx_cache_dir: "/var/cache/mediamtx"

stream_source: "rpiCamera"
sourceOnDemand: true
rtsp_enable: "no"
rtpm_enable: "no"
hls_enable: "no"
webrtc_enable: "yes"
srt_enable: "no"
