---
apt_packages:
  - acl
  - git
  - nginx
  - redis
  - redis-server
  - zabbix-agent
  - zabbix-sender
  - libmodbus5
  - ffmpeg
  - libcap-dev
  - libfreetype6-dev
  - libopenjp2-7
  - libtiff6
  - libgpiod3
  - libgpiod-dev
  - libjpeg-dev
  - libgpiod3
  - libgpiod-dev
  - build-essential
  - python3-pip
  - python3-dev
  - python3-wheel
  - python3-packaging
  - python3-setuptools
  - python3-numpy
  - python3-gpiozero
  - python3-lgpio
  - python3-rpi-lgpio
  - python3-picamera2
  - python3-systemd
  - python3-smbus 
  - libi2c-dev
  - i2c-tools
  - libi2c0
  - read-edid
