---
apt_packages:
  - apache2-utils
  - nginx
  - redis
  - redis-server
  - git
  - ffmpeg
  - libfreetype6-dev
  - libopenjp2-7
  - libtiff6
  - libgpiod3
  - libgpiod-dev
  - libjpeg-dev
  - build-essential
  - python3-pip
  - python3-dev
  - python3-numpy
  - python3-gpiozero
  - python3-picamera2
  - python3-systemd
  - python3-setuptools
  - python3-wheel
  - python3-packaging
  - libgpiod3
  - libgpiod-dev
  - zabbix-agent
  - gunicorn
