---
setup:
  verbose: false
  show_sys_info: false
  use_system_buttons: false
  use_door_led_indicator: false
  use_motion_led_indicator: false
  use_door_sensor: false
  use_motion_sensor: false
  use_bme280_sensor: true
  use_ds18b20_sensor: false
  use_dht_sensor: false
  use_cpu_sensor: true
  use_weather_station: false
  use_zabbix_sender: false
  use_picamera: true
  use_picamera_recording: false
  use_serial_display: false
  serial_display_type: lcd_st7735
  serial_type: spi
  serial_display_refresh_rate: 10
  serial_display_rotate: 0
zabbix_agent:
  TLSAccept: psk
  TLSConnect: psk
  TLSPSK: a82a2481fb15458818139362a321c2abc1324cdd0cb3b76e386168fae8d2f964
  TLSPSKFile: /opt/RPiMS/config/zabbix_rpims.psk
  TLSPSKIdentity: 697df0c2978b7338
  Timeout: 3
  hostname: rpims.home
  location: My Home
  chassis: embedded
  deployment: RPiMS
  zabbix_server: zabbix.home
  zabbix_server_active: zabbix.home
gpio:
  GPIO_5:
    pin: 5
    type: MotionSensor
    name: motion sensor in room 1
    hold_time: 1
  GPIO_6:
    pin: 6
    type: MotionSensor
    name: motion sensor in room 2
    hold_time: 1
  GPIO_12:
    pin: 12
    type: door_led
    name: door led
    hold_time: ''
  GPIO_13:
    pin: 13
    type: MotionSensor
    name: motion sensor in room 3
    hold_time: 1
  GPIO_16:
    pin: 16
    type: DoorSensor
    name: door in room 1
    hold_time: 1
  GPIO_18:
    pin: 18
    type: motion_led
    name: motion led
    hold_time: ''
  GPIO_19:
    pin: 19
    type: DoorSensor
    name: door in room 2
    hold_time: 1
  GPIO_20:
    pin: 20
    type: DoorSensor
    name: door in room 3
    hold_time: 1
  GPIO_21:
    pin: 21
    type: Reserved
    name: not used
    hold_time: 1
  GPIO_26:
    pin: 26
    type: Reserved
    name: not used
    hold_time: 1
sensors:
  CPU:
    temp:
      read_interval: 1
  PICAMERA:
    fps: 24
    mode: 6
    vflip: false
    hflip: false
    vr: 720
    hr: 1280
  BME280:
    id1:
      i2c_address: 118
      interface: i2c
      name: Room 1
      read_interval: 2
      use: false
      id: id1
    id2:
      serial_port: USB1
      interface: serial
      name: Room 2
      read_interval: 2
      use: false
      id: id2
    id3:
      serial_port: USB2
      interface: serial
      name: Room 3
      read_interval: 6
      use: true
      id: id3
  ONE_WIRE:
    DS18B20:
      addresses: {}
      read_interval: 5
  DHT:
    name: Outoor
    pin: 17
    read_interval: 60
    type: DHT11
  WEATHER:
    RAINFALL:
      acquisition_time: 60
      agregation_time: 3600
      sensor_pin: 22
      use: false
    WIND:
      DIRECTION:
        acquisition_time: 6
        adc_input: 1
        adc_type: AutomationPhat
        reference_voltage_adc_input: 2
        use: false
      SPEED:
        acquisition_time: 6
        agregation_time: 3600
        sensor_pin: 23
        use: false
