---
- name: System packet update
  apt:
    update_cache: yes

- name: System packet upgrade
  apt:
    upgrade: dist

- name: System packet autoremove 
  apt:
    autoremove: yes

- name: Setting time/zone
  timezone:
    name: "{{ timezone_name }}"

- name: Setting the hostname
  hostname:
    name: "{{ raspi_hostname }}"

- name: Adding a new hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ raspi_hosts_ip }}   {{ raspi_hostname }}"
    state: present

