---
- name: Konfiguracja Raspberry Pi
  hosts: rpims
  become: yes

  roles:
    - { role: system,     tags: ['system'] }
    - { role: packages,   tags: ['packages'] }
    - { role: python,     tags: ['python'] }
    - { role: hardware,   tags: ['hardware'] }
    - { role: redis,      tags: ['redis'] }
    - { role: deploy,     tags: ['deploy'] }
    - { role: validation, tags: ['validation'] }
