---
- name: RPiMS deploying
  hosts: rpims
  become: yes

  roles:
    - { role: system,          tags: ['system'] }
    - { role: packages,        tags: ['packages'] }
    - { role: usb_automount,   tags: ['usb_automount'] }
    - { role: hardware,        tags: ['hardware'] }
    - { role: deploy,          tags: ['deploy'] }
    - { role: validation,      tags: ['validation'] }
