---
- name: RPiMS deploying
  hosts: rpims
  become: true

  roles:
    - role: system
      tags: system

    - role: packages
      tags: packages

    - role: hardware
      tags: hardware

    - role: validation
      tags: validation

    - role: usb_automount
      tags: usb_automount

    - role: deploy
      tags: deploy
