- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted

- name: Enable and start rpims-gunicorn.service
  systemd:
    name: rpims-gunicorn.service
    enabled: yes
    state: started
